### ISSUE TITLE
ClassCastException Error on RN 0.42.0

### ISSUE THREAD

**Issue by nzwnabdulwahid** [maicki/react-native-event-bridge#16]
I am running on RN 0.42.0 and when I try to emit an event onClick, it issue me this error : 

`AndroidJavaException: java.lang.ClassCastException: android.app.Application cannot be cast to net.mischneider.MSREventBridgeInstanceManagerProvider
                                                             java.lang.ClassCastException: android.app.Application cannot be cast to net.mischneider.MSREventBridgeInstanceManagerProvider`

and I believe it occurs at this line : 
`MSREventBridgeInstanceManagerProvider instanceManagerProvider =
                (MSREventBridgeInstanceManagerProvider)this.getApplicationContext();`

Anyone encounter this before ?

**Comment by maicki** [comment]
Hey @nzwnabdulwahid, does your Application implements the `MSREventBridgeInstanceManagerProvider` interface? Look at `MainApplication.java` how this should look like.

**Comment by maicki** [comment]
@nzwnabdulwahid Were you able to try out my recommendation yet from above yet?

**Comment by nzwnabdulwahid** [comment]
Hi @maicki sorry I forgot to update here yes thanks a lot !
