### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by mrackwitz** [maicki/react-native-event-bridge#19]
I was seeing nullability warnings with version 0.7.0, which were already fixed by #17. It would be nice if these changes could be released on NPM.

**Comment by maicki** [comment]
@mrackwitz Hey! Update just created a realease PR: #21 for version 0.8.0. I hope to release it at the latest Monday.

**Comment by maicki** [comment]
Version 0.8.0 should be available via npm now.
