### ISSUE TITLE
Method does not override method from its superclass

### ISSUE THREAD

**Issue by kckunal2612** [maicki/react-native-event-bridge#20]
After integrating the module, when I run '`react-native run-android`', the build fails at this error message, in the MSREventBridge class.

**Versions**
- "react": "16.0.0",
- "react-native": "0.50.3"

**Comment by maicki** [comment]
@kckunal2612 Hey, can you post in the exact error message to see which method is not overwritten? Thanks!

**Comment by maicki** [comment]
We just released version 0.8.0 , so just update your npm dependencies and it should resolves this issue.

**Comment by kckunal2612** [comment]
Thanks for the reply ! So, I updated the dependencies (now on version 0.8.0) and now I get a different error in the debugger console.

> Invariant Violation: If you would like receive events you have to define the reactTag in your contexts. Component: App


Here's my code (React Native and Android Native both) -

**React Native**

```
export default class App extends Component<{}> {

    _eventSubscription: ?EmitterSubscription;

    componentDidMount() {
        console.log("componentDidMount");
        // Register for an event that will be sent from the native side
        /* eslint-disable no-unused-vars */ // For some reason info is marked as unused :/
        this._eventSubscription = EventBridge.addEventListener(
            this,
            (name, info) => {
                /* eslint-enable no-unused-vars */
                console.log(
                    `Received event from native: ${name} with info: {JSON.stringify(info)}`
                );
            }
        );
    }
......
}
```

**Android**
```

private void sendNotification(Context context) {
        Log.e("sendNotification", "SHOW NOTIFICATION");
        // Emit event via MSREventBridgeModule
        WritableMap map = new WritableNativeMap();
        map.putString("rowSelected", "10");
        MSREventBridgeModule.emitEventContext(context, "eventName", map);
    }
```

**Comment by maicki** [comment]
@kckunal2612 I think the `README` is not up to date. I think in your case you have to `import PropTypes from 'prop-types'` and use for `contextTypes`: 
```
static contextTypes = {
    rootTag: PropTypes.number,
};
```

You can also find more information about why the React team moved the PropTypes into an external lib in here: https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by maicki** [comment]
@kckunal2612 See my comment from above, that should resolve your issue. Otherwise let me know and we will reopen the issue. Thanks!

**Comment by kckunal2612** [comment]
Hi. So that issue got solved when I followed your comment, but now I keep getting this error -
```

 E/unknown:ReactNative: Exception in native call java.lang.ClassCastException: 
com.test.MainApplication cannot be cast to net.mischneider.MSREventBridgeInstanceManagerProvider
                                                                 at com.test.MainActivity.onEventCallback(MainActivity.java:49)
```

even though I have followed the example app given here.

Please see the gist below for the code -

https://gist.github.com/kckunal2612/1311ec0cfaff27c5ff2c1890a69c25a2

**Comment by thorbenprimke** [comment]
@kckunal2612  - Please make sure your `Application` implements `MSREventBridgeInstanceManagerProvider ` 

See - https://github.com/maicki/react-native-event-bridge/blob/master/example/android/app/src/main/java/com/eventbridgeexample/MainApplication.java

**Comment by kckunal2612** [comment]
Worked perfectly now ! Thanks a ton ! :+1:

**Comment by maicki** [comment]
Awesome. Seems like @thorbenprimke was faster than me to figure out the last blocker :) Glad it works for you know.
