### ISSUE TITLE
Need help: iOS Integration

### ISSUE THREAD

**Issue by ma-pe** [maicki/react-native-event-bridge#24]
Hi, 

first of all: thanks for making this library!

I am trying to integrate a React-Native-View into a native App. Once a button in React-Native is pressed, I want the native app to get notified. Therefore I tried to integrate your library.

I wasn't able to automatically link (#23), but manual linking was successful.

Now here is my code:

`#import <MSREventBridge/MSREventBridge.h>`
`@interface AppDelegate : UIResponder <UIApplicationDelegate, MSREventBridgeEventReceiver>`

XCode says: `MSREventBridge/MSREventBridge.h' file not found`

What am I doing wrong?

**Comment by ma-pe** [comment]
PS: Android works just fine. You could add an advice to the readme that the native component needs `implements MSREventBridgeEventReceiver`.

**Comment by maicki** [comment]
@ma-pe Hey - I just linked the lib with a new RN project that I bootstrapped via `react-native init` and the linking worked for iOS and Android. How is your RN project structured? Is it bootstrapped via `react-native init` or uses Cocoapods etc?

I will update the Documentation to include the import statements. Try `#include MSREventBridge.h` for now.

**Comment by ma-pe** [comment]
@maicki 
Thanks for helping.
My current project is an ejected project that was bootstrapped with `create-react-native-app`. 

I tried `#include "MSREventBridge.h"` but this also says `'MSREventBridge.h' file not found`.

**Comment by ma-pe** [comment]
@maicki 
Since I did the manual linking I wonder if the setup guide is complete. I added the corresponding `.xcodeproj` to the `Libraries` folder:

![image](https://user-images.githubusercontent.com/7078893/34981930-52dc3996-faa9-11e7-9047-2001ecf244be.png)

and I included the lib to `Build Phases -> Link Binary With Libraries`:

![image](https://user-images.githubusercontent.com/7078893/34982037-869200d6-faa9-11e7-8205-3933c1b41724.png)

Building the App works, but referencing the lib via `#include` or `#import` fails as described above.

Any ideas?

**Comment by maicki** [comment]
@ma-pe Did you also add the path to the "Header Search Path"? There is also a Manual Linking section in the RN documentation: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by ma-pe** [comment]
@maicki that was the issue. Import works like a charme now.

Now I am just stumbling about this issue in my App:

![image](https://user-images.githubusercontent.com/7078893/35002803-15d3bd16-faeb-11e7-94ed-52655cc67e01.png)

An ideas on this?

**Comment by maicki** [comment]
@ma-pe Which version do you use? If you look into `MSREventBridge.m/h` the `onEvent:name:info:` should have a `nonnull` annotation for `reactTag`.

**Comment by ma-pe** [comment]
I use the current release 0.8.0. There is no `nonnull` annotation for `reactTag`. 

Seems that it was removed with this commit: https://github.com/maicki/react-native-event-bridge/commit/979b10cee2465629b2a6fef495a353cfa1c849f7.

**Comment by ma-pe** [comment]
@maicki when I add the `nonnull` annotation there is no error anymore. But it also happens nothing.

Here is my code:

**JS**
`EventBridge.emitEvent(this, 'ShowNextView');`

**AppDelegate.h**
`#import "MSREventBridge.h"`
`@interface AppDelegate : UIResponder <UIApplicationDelegate, MSREventBridgeEventReceiver>`

**AppDelegate.m**
`- (void)onEventWithName:(NSString *)eventName info:(nullable NSDictionary *)info`
`{ printf("test"); }`

I expected 'test' to be printed to XCode Console every time I emit the Event.

**Comment by maicki** [comment]
@ma-pe Did you look at the examples and run them? You may have a better idea after that how this plays together ... otherwise could you create an example project that shows your problem so I can look into it more deeper? Thanks!

**Comment by ma-pe** [comment]
That was it. Thank you very much! :-)

**Comment by ma-pe** [comment]
I had to add the `nonnull` annotation to the reactTag at onEvent, though:

MSREventBridge.m / Line 36
`RCT_EXPORT_METHOD(onEvent:(nonnull NSNumber *)reactTag name:(NSString *)name info:(NSDictionary *)info)`

You should add this to the master-branch :-) Thank you!

**Comment by maicki** [comment]
@ma-pe I already aded the `nonnull` to the master branch on Saturday or so. Should go out soon with a new release.

I will close this issue for now than as it seems it's working now.
