### ISSUE TITLE
Argument 0 (NSNumber) of MSREventBridge.onEvent has unspecified nullability but React requires that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.

### ISSUE THREAD

**Issue by kumarargutech** [maicki/react-native-event-bridge#28]
Hi team,

We are facing some problems in react-native-event-bridge, Our scope, event emit react native app to native app (iOS and Andriod).

**In react native ap code :**

handleEventEmitter() {
    EventBridge.emitEventCallback(this, 'EventWithCallback', () => { 
     console.log('welcome-event');
    });
 }

**In iOS Code :**

   // MARK: MSREventBridgeEventReceiver
extension VNNetworkSecurityViewController: MSREventBridgeEventReceiver {
    // MARK: Handle events from RN
    func onEvent(withName name: String?, info: [AnyHashable : Any]?, callback: RCTResponseSenderBlock!) {
        print("Received event with callback: \(name) welcome")
        callback([])
    }
}

Got Error message : 

**Argument 0 (NSNumber) of MSREventBridge.onEvent has unspecified nullability but React requires that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.**

**Comment by maicki** [comment]
@kumarargutech I didn't put out a release yet but it's already fixed on master. Can you use that for the time being. Thanks!

**Comment by kumarargutech** [comment]
@maicki Thanks for your response.

**Comment by andrei-tara** [comment]
I have the same issue, and got the master sources, any idea how to make it work ?

**Comment by maicki** [comment]
@andrei-tara This should work with latest master. Can you please double check if you really got latest master? How does your `package.json` entry for `react-native-event-bridge` looks like?

**Comment by andrei-tara** [comment]
Yes, this is what I got in package.json
 "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-event-bridge": "git://github.com/maicki/react-native-event-bridge#c398d14879c8b21442b550808ee856053a1fb18e"
  },

**Comment by maicki** [comment]
@andrei-tara Can you look into `MSREventBridge.m` in the `node_modules` folder of `react-native-event-bridge` and look if the nullability annotations are there?

**Comment by andrei-tara** [comment]
I don't see it here is the file content 
`//
//  MSREventBridge.m
//
//  Created by Michael Schneider
//  Copyright © 2017 mischneider. All rights reserved.
//

#import "MSREventBridge.h"

#import <React/RCTUIManager.h>
#import <React/RCTLog.h>

#pragma mark -
#pragma mark - MSREventBridge

@interface MSREventBridge () <RCTBridgeModule>

@end

@implementation MSREventBridge

#pragma mark <MSREventBridge>

RCT_EXPORT_MODULE();

#pragma mark Queue

- (dispatch_queue_t)methodQueue
{
  // All events will be handled on the main thread
  return dispatch_get_main_queue();
}

#pragma mark Receive Events

RCT_EXPORT_METHOD(onEvent:(nonnull NSNumber *)reactTag name:(NSString *)name info:(NSDictionary *)info)
{
  [self.bridge.uiManager rootViewForReactTag:reactTag withCompletion:^(UIView *rootView) {
    // Check if root view can receive the event
    if ([rootView conformsToProtocol:@protocol(MSREventBridgeEventReceiver)]
        && [rootView respondsToSelector:@selector(onEventWithName:info:)]) {
      [(id<MSREventBridgeEventReceiver>)rootView onEventWithName:name info:info];
    }
    
    // Check if the view controller of the root view can receive the event
    UIViewController *viewController = rootView.reactViewController;
    if ([viewController conformsToProtocol:@protocol(MSREventBridgeEventReceiver)]
        && [viewController respondsToSelector:@selector(onEventWithName:info:)]) {
      [(id<MSREventBridgeEventReceiver>)viewController onEventWithName:name info:info];
    }
  }];
}

RCT_EXPORT_METHOD(onEventCallback:(nonnull NSNumber *)reactTag name:(NSString *)name info:(NSDictionary *)info callback:(RCTResponseSenderBlock)callback)
{
  [self.bridge.uiManager rootViewForReactTag:reactTag withCompletion:^(UIView *rootView) {
    // Check if root view can receive the event
    if ([rootView conformsToProtocol:@protocol(MSREventBridgeEventReceiver)]
        && [rootView respondsToSelector:@selector(onEventWithName:info:callback:)]) {
      [(id<MSREventBridgeEventReceiver>)rootView onEventWithName:name info:info callback:^(NSError *error, id data) {
        callback(@[(error ?: [NSNull null]), (data ?: [NSNull null])]);
      }];
    } else {
      // Check if the view controller of the root view can receive the event
      UIViewController *viewController = rootView.reactViewController;
      if ([viewController conformsToProtocol:@protocol(MSREventBridgeEventReceiver)]
          && [viewController respondsToSelector:@selector(onEventWithName:info:callback:)]) {
        [(id<MSREventBridgeEventReceiver>)viewController onEventWithName:name info:info callback:^(NSError *error, id data) {
          callback(@[(error ?: [NSNull null]), (data ?: [NSNull null])]);
        }];
      }
    }
  }];
}

#pragma mark Emit Events

// Static Identifier for events that are sent to React Native. These needs to be in sync with Android!
static NSString * const MSREventBridgeModuleEventName = @"MSREventBridgeModuleEvent";
static NSString * const MSREventBridgeModuleEventReactTagKey = @"reactTag";
static NSString * const MSREventBridgeModuleEventNameKey = @"eventName";
static NSString * const MSREventBridgeModuleEventInfoKey = @"info";

// We export the the event name to have a constant in React Native
- (NSDictionary *)constantsToExport
{
  return @{
    @"EventName": MSREventBridgeModuleEventName,
    @"EventReactTagKey" : MSREventBridgeModuleEventReactTagKey,
    @"EventNameKey" : MSREventBridgeModuleEventNameKey,
    @"EventInfoKey" : MSREventBridgeModuleEventInfoKey
  };
}

- (NSArray<NSString *> *)supportedEvents
{
  return @[MSREventBridgeModuleEventName];
}

- (void)emitEventWithName:(NSString *)name info:(NSDictionary *)info
{
  [self sendEventWithName:MSREventBridgeModuleEventName body:@{
    MSREventBridgeModuleEventNameKey : name,
    MSREventBridgeModuleEventInfoKey : info
  }];
}

- (void)emitEventForView:(UIView *)view name:(NSString *)name info:(NSDictionary *)info
{
  // Emit an event to a component that is within the view hierarchy of the root view. Therefore use
  // the root view's react tag as identifier
  UIView *rootView = view;
  while (rootView.superview && ![rootView isKindOfClass:RCTRootView.class]) {
    rootView = rootView.superview;
  }
  
  NSAssert([rootView isKindOfClass:RCTRootView.class], @"Events send to a specific view needs to be of kind RCTRootView");
  
  [self sendEventWithName:MSREventBridgeModuleEventName body:@{
    MSREventBridgeModuleEventReactTagKey : rootView.reactTag,
    MSREventBridgeModuleEventNameKey : name,
    MSREventBridgeModuleEventInfoKey : info
  }];
}

@end

#pragma mark -
#pragma mark - RCTBridge (MSREventBridgeModule)

@implementation RCTBridge (MSREventBridgeModule)

- (id<MSREventBridgeEventEmitter>)viewControllerEventEmitter
{
  return [self moduleForClass:[MSREventBridge class]];
}

@end
`

**Comment by maicki** [comment]
@andrei-tara it seems like you didn't install the latest from master than.

Can you try: "react-native-event-bridge": "git://github.com/maicki/react-native-event-bridge"

**Comment by maicki** [comment]
I just published version 0.9.0 on npm that should fix this issue.
