### ISSUE TITLE
Argument 0 (NSNumber) of MSREventBridge.onEvent must not be null

### ISSUE THREAD

**Issue by kumarargutech** [maicki/react-native-event-bridge#29]
Hi Team,

Am using React-native-event-bridge npm packge. Trigger the onPress event to display the error in ios device.

Event Trigger in react native:

<TouchableOpacity onPress={() => EventBridge.emitEvent(this, 'PresentScreen')
}>
<Text> Go to back </Text>
</TouchableOpacity> 

Log :
Argument 0 (NSNumber) of MSREventBridge.onEvent must not be null
2018-03-20 22:47:21.442 [error][tid:main][RCTModuleMethod.mm:69] Argument 0 (<null>) of MSREventBridge.onEvent could not be processed. Aborting method call.

**Comment by joshuadelange** [comment]
I also had this error but was able to resolve it by placing the event emitter in `componentDidMount`. For what I need this works fine, but not sure if that helps you.

**Comment by maicki** [comment]
@kumarargutech What component is `this` in this case?

**Comment by ma-pe** [comment]
I am experiencing the same in only one of my views.

I have a view that returned `null` - which is valid. I use it as a proxy, that does thinks like routing, but doesn't have a ui representation (yet).

`findNodeHandle(this)` will return ... `null`.

This is an easy fix, now my Component returns `<View/>`. And `findNodeHandle(this)` returns something - and the error vanished - perfect.

We could add an advice to the docs for this case.

**Comment by kumarargutech** [comment]
Thanks @ma-pe

**Comment by maicki** [comment]
Closing this Issue. For further information please see: #48
