### ISSUE TITLE
Sending `MSREventBridgeModuleEvent` with no listeners registered.

### ISSUE THREAD

**Issue by joshuadelange** [maicki/react-native-event-bridge#31]
Hi there,

Thank you so much for creating this library!!

I was able to implement the events on iOS going from React Native to native fine, but now I want to send an event back and I'm having troubles.

I receive the following error: `Sending 'MSREventBridgeModuleEvent' with no listeners registered`. I've tried all kinds of things and I have copied pretty much most of your code from the example, but doesn't seem to want to work.

Any ideas on what I'm doing wrong would be very appreciated.

Thank you!

**Native**
```
// After receiving an event send some event back with name `eventName`.
[self.viewControllerEventEmitter emitEventForView:self.view name:@"eventName" info:@{
  @"UUID" : _UUID.UUIDString,
  @"data" : @"data"
}];
```

**React**
```
// Register for an event that comes from native
this._eventSubscription = EventBridge.addEventListener(this, (name, info) => {
  this.setState({bg: 'pink'});
  console.log("Received event from native: '" + name + "' with info: " + JSON.stringify(info));
});
```

Let me know if you need more information.

**Comment by maicki** [comment]
@joshuadelange Hey - would you mind creating a sample RN project that would show the error, so I can debug in detail what is going on? Thanks!

**Comment by andrei-tara** [comment]
I have the same issue:

On JS:
  EventBridge.emitEventInfoCallback(this, 'Login', {'profile': 1}, (error, result) => {
            console.log(result);
        });

On Swift:

self.sendEvent(withName:"Login", info: [:])


func sendEvent(withName name: String!, info: [AnyHashable : Any]!) {
        if let rootView = self.view as? RCTRootView, let bridge = rootView.bridge {
            // Send an event to components subscribed in the root view
            bridge.viewControllerEventEmitter.emitEvent(for: rootView, name: name, info: info)
        }
    }

**Comment by maicki** [comment]
Closing this Issue. For further information please see: #48
