### ISSUE TITLE
iOS: 'onEventWithName' not called after updating to RN 0.54.4

### ISSUE THREAD

**Issue by ma-pe** [maicki/react-native-event-bridge#33]
Hey,

my previously working event-bridge (RN 0.53.0) stopped working after upgrading to RN 0.54.4. The 'onEventWithName' method on iOS is not called anymore.

Any ideas?

**Comment by maicki** [comment]
@ma-pe I cannot reproduce this. See the attached sample project.
[EventBridgeLatestRN.zip](https://github.com/maicki/react-native-event-bridge/files/1872261/EventBridgeLatestRN.zip)

**Comment by ma-pe** [comment]
Thank you. I downgraded to 0.53.0 again - will check that in the following weeks. Maybe there is an issue with my "special setup" communicating with the RootViewController (`@interface RootViewController : UIViewController <MSREventBridgeEventReceiver>`).

I'll let you know soon.

**Comment by maicki** [comment]
@ma-pe Do you still see issues with the latest version of RN?

**Comment by ma-pe** [comment]
I will update to react-native in the following days. I'll comment here, once I have new information.

**Comment by ma-pe** [comment]
I cannot reproduce this issue. Seems to work fine. Thanks for your patience.
