### ISSUE TITLE
2 RootView in one activity

### ISSUE THREAD

**Issue by xincubate** [maicki/react-native-event-bridge#34]
if there are 2 "RootView" in one acitivity, the logic in "MSREventBridgeModule.findReactRootView" would be found the first "RootView"，so all the event which will send to the second "RootView" are wrong，becasue they are sended to the first "RootView"。。。

this issue can be fix while find all the "RootView" in "MSREventBridgeModule.findReactRootView" ,otherwise find the first  "RootView"

**Comment by maicki** [comment]
Addressed via #37
