### ISSUE TITLE
emitting event from native ios working example

### ISSUE THREAD

**Issue by deepakverma4** [maicki/react-native-event-bridge#39]
Can you please share an working example of how to emit event from native ios? The one in the repo is complex as all the work is done inside only one appdelegate.m file.

**Comment by bbubn** [comment]
The same problem. I am eager to find a working example ...

**Comment by objectiveSee** [comment]
@bbubn did you see this? https://github.com/maicki/react-native-event-bridge#ios-2

**Comment by bbubn** [comment]
@objectiveSee Yep, but the example is not completed I don't get how to use it. I try a few variants and always have same problem with  RCTBridge (because it in another module/project)

**Comment by anfriis** [comment]
Yeah the sample code is not working. Check the `EventBridgeExample` for a working implementation

**Comment by maicki** [comment]
Unfortunately I don't have some time in the near future to look into this. I would appreciate if someone would be so kind and open a PR that would fix the sample code within the README. Thanks!

**Comment by flexaddicted** [comment]
@maicki I've opened a PR to fix the code in example-swift.

**Comment by maicki** [comment]
Closing this Issue. For further information please see: #48
